# Declare variables to be passed into your templates.
#
replicaCount: 1
image:
  repository: kaigara/gerrit
  tag: 0.0.5
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  http:
    externalPort: 8080
    internalPort: 8080
  ssh:
    externalPort: 29418
    internalPort: 29418
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 1
    memory: 512Mi
persistence:
  enabled: false
  storageClass: generic
  accessMode: ReadWriteMany
  size: 8Gi

basePath: "/var/gerrit/review_site/git"
database:
  database: "reviewdb"
  username: "gerrit"
  password: "changeme"
global:
  domain: devstack.local
  mariadbRootPassword: changeme
  LdapAdminPassword: changeme
