apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
    name: http
    protocol: TCP
  - port: {{ .Values.service.ssh.externalPort }}
    targetPort: {{ .Values.service.ssh.internalPort }}
    name: ssh
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
